libavcodec/x86/vvc_alf.asm
libavcodec/x86/vvcdsp.h
libavcodec/x86/vvcdsp_init.c

benchmarking with native FFmpeg timers
nop: 28.8
checkasm: using random seed 1318232087
AVX2:
- vvc_alf.alf_filter [OK] checkasm: all 256 tests passed
vvc_alf_filter_chroma_4x4_8_c: 653.3
vvc_alf_filter_chroma_4x4_8_avx2: 133.5
vvc_alf_filter_chroma_4x4_10_c: 597.5
vvc_alf_filter_chroma_4x4_10_avx2: 134.3
vvc_alf_filter_chroma_4x8_8_c: 1290.0
vvc_alf_filter_chroma_4x8_8_avx2: 252.0
vvc_alf_filter_chroma_4x8_10_c: 1235.3
vvc_alf_filter_chroma_4x8_10_avx2: 251.3
vvc_alf_filter_chroma_4x12_8_c: 1865.5
vvc_alf_filter_chroma_4x12_8_avx2: 375.5
vvc_alf_filter_chroma_4x12_10_c: 1791.8
vvc_alf_filter_chroma_4x12_10_avx2: 1045.3
vvc_alf_filter_chroma_4x16_8_c: 2557.8
vvc_alf_filter_chroma_4x16_8_avx2: 499.0
vvc_alf_filter_chroma_4x16_10_c: 2426.0
vvc_alf_filter_chroma_4x16_10_avx2: 489.5 …

alf_filter: add 8 bits support

---

libavcodec/vvc_ctu.h
libavcodec/vvc_filter.c
libavcodec/vvc_filter_template.c
libavcodec/vvcdec.h
libavcodec/vvcdsp.h
tests/checkasm/vvc_alf.c

This is based on a review comment from Ronald 
> 2023-02-26 21:18:40     @BBB    Nuo: hi!
> 2023-02-26 21:18:49     @BBB    Nuo: C code is similar to your C code: https://code.videolan.org/videolan/dav1d/-/blob/master/src/loopfilter_tmpl.c
> 2023-02-26 21:19:20     @BBB    the h26x code tends to be a bit more complex because of the adaptive parameters (coded in bitstream, or based on q, etc.)
> 2023-02-26 21:19:25     @BBB    but the per-pixel stuff is not super-different
> 2023-02-26 21:20:06     @BBB    if you look at the loops below, you'll see the intended use by the simd, it's fairly obvious: do super-big blocks with many parameters to use the vector size as efficiently as possible
> 2023-02-26 21:20:29     @BBB    e.g. https://code.videolan.org/videolan/dav1d/-/blob/master/src/x86/lo …

Do alf filter on a CTU instead of 32x32 block.

---

.github/workflows/makefile.yml

This PR adds CI for windows using [FFVS-Project-Generator](https://github.com/ShiftMediaProject/FFVS-Project-Generator). The steps are generally similar to the existing linux CI jobs, with one significant difference: as FFVS-Project-Generator does not currently support disabling assembly optimisations (see ShiftMediaProject/FFVS-Project-Generator#62), the Windows build is currently performed with assembly enabled and assembled using NASM.
One test (LTRP_A_ERICSSON_3) is actually [failing right now](https://github.com/frankplow/FFmpeg/actions/runs/4499236849/jobs/7916843917), and due to a mismatch rather than a timeout. I don't believe this is an issue with the CI configuration however. I would imagine the issue is in the assembly optimisations, rather than some OS/compiler-specific …

Continuous integration job for Windows/MSVC

---

.github/workflows/makefile.yml

Fix negation of the exitcode for the expected-to-fail tests on the Windows CI runner.
* Check `$LASTEXITCODE` rather than `$?`
* Produce an error/success explicitly with `exit` rather than by throwing or not throwing
* Test code ≠ 0 rather than = 1

Fix CI powershell exitcode negation

---

.github/workflows/makefile.yml

This PR adds two new jobs to CI for building and testing with assembly optimisations enabled and assembled with NASM and YASM on Windows.
Different operating systems are now combined into a single matrix as this is easier to manage with all the combinations of OS/compiler/assembler. I think this will also be more future-proof as different checks and combinations are added. This required using MSYS/MSVC instead of FFVS-Project-Generator. If we still want to check FFVS-Project-Generator can generate a valid VS solution in CI I can add this as a separate job.
The new jobs have flagged an [error when compiling with YASM](https://github.com/frankplow/FFmpeg/actions/runs/4707830898/jobs/8349932081).

Add Windows builds with assembly optimisations enabled to CI

---

.github/workflows/makefile.yml

This PR adds checkasm to the GitHub Actions workflow using a Windows runner. At the minute, the [test is failing](https://github.com/frankplow/FFmpeg/actions/runs/4714065453/jobs/8360173070) with `failed to preserve register`. Not sure if this is something we can work around? The same configure flags work fine on my local machine
This PR will close #63.

Add checkasm to CI

---

configure
libavcodec/Makefile

./configure --disable-everything --enable-decoder=vvc && make -j
error:
/usr/bin/ld: libavcodec/libavcodec.a(vvcdec.o): in function `decode_nal_units': /home/nuomi/codec/ffmpeg/libavcodec/vvcdec.c:942: undefined reference to `ff_h2645_packet_split' /usr/bin/ld: libavcodec/libavcodec.a(vvcdec.o): in function `frame_context_free': ...

build: fix standalone build fail for decoder

---

libavcodec/cbs_h266_syntax_template.c
libavcodec/vvc/vvc_ps.c
libavcodec/vvc/vvcdsp.c
libavcodec/vvc_parser.c

This PR adds support for 12-bit colour.
This is a draft as the tests are currently failing. Below shows a still from 12b444vvc1_B_Sony_2. There appears to be some coloured artefacts on the centre and left of the screen. Without wishing to jump to conclusions, I suspect this is an issue with the inter-prediction code.
When using a bit depth higher than 10, the standard allows a bitstream to include the range extension in the SPS. In practice, most do this as this is required to enable the `sps_extended_precision_flag`, which increases dynamic range. There are, however, a handful of conformance bitstreams which use 12-bit colour without the range extension:
* 12b420Ivvc1_A_InterDigital_2
* 12b420SPvvc1_A_KDDI_2
* 12b420vvc1_A_Alibaba_2
* 12b444Ivvc1_A_Alibaba_2
* 12b444SPvvc1_A_Alibaba_2
* …

12-Bit Support

---

libavcodec/vvc/vvc_data.c
libavcodec/vvc/vvc_data.h
libavcodec/vvc/vvc_filter.c
libavcodec/vvc/vvc_filter_template.c
libavcodec/vvc/vvc_ps.c
libavcodec/vvc/vvc_ps.h
libavcodec/vvc/vvcdsp.h
libavcodec/x86/vvc_alf.asm
libavcodec/x86/vvcdsp.h
libavcodec/x86/vvcdsp_init.c
tests/checkasm/vvc_alf.c

on a i7-12700:
clips|before|after|delta|
-|-|-|-|
RitualDance_1920x1080_60_10_420_32_LD.266 | 128.0 | 135.7|6.02%|
Tango2_3840x2160_60_10_420_27_RA.266 | 33.7 |36.0|6.82%|
RitualDance_1920x1080_60_10_420_37_RA.266 | 146.0 |155.7|6.64%|
Tango2_3840x2160_60_10_420_27_LD.266 | 32.3 |35.0 |8.36%|
BQTerrace_1920x1080_60_10_420_22_RA.vvc | 80.7 |85.3|5.70%|
NovosobornayaSquare_1920x1080.bin | 149.7 |156.3|4.41%|
Chimera_8bit_1080P_1000_frames.vvc | 161.3 |170.0|5.39%|

Implement alf filter vb.

---

libavcodec/vvc/vvcdsp.h
libavcodec/x86/Makefile
libavcodec/x86/vvc_sao.asm
libavcodec/x86/vvc_sao_10bit.asm
libavcodec/x86/vvcdsp_init.c
tests/checkasm/Makefile
tests/checkasm/checkasm.c
tests/checkasm/checkasm.h
tests/checkasm/vvc_sao.c

I have imported the assembly SAO Band and Edge filters from HEVC. There are some issues, which is why I'm marking this as draft for now. 
- ~~The SAO Edge Filter currently does not work as expected~~ (FIXED)
- ~~We currently only have the same accelerated functions as HEVC. We do not have all functions needed to handle all possible CTU sizes for VVC. Locally, I got `vvc_sao_band_80_8_avx2` to pass `checkasm`, but not the 10-bit version, and `checkasm` causes a segfault on adding other CTU sizes~~ (FIXED)
- ~~No 12-bit support.~~ (FIXED)
I did some benchmarks with just the band filter enabled, and the performance the AVX2 and C versions are equal. Further research leads me to believe that this is expected behavior, since more blocks go thru the edge filter rather than the band filter. …

vvc_sao: Import AVX2 accelerated SAO filters from HEVC

---

libavcodec/vvc/vvc_filter_template.c
libavcodec/vvc/vvcdsp.h

libavcodec/vvc/vvc_filter_template.c: In function ‘ff_vvc_sao_dsp_init_10’: libavcodec/vvc/vvc_filter_template.c:1074:29: warning: assignment to ‘void (*)(uint8_t *, const uint8_t *, ptrdiff_t,  ptrdiff_t,  const int16_t *, const int,  const int,  const int)’ {aka ‘void (*)(unsigned char *, const unsigned char *, long int,  long int,  const short int *, const int,  const int,  const int)’} from incompatible pointer type ‘void (*)(uint8_t *, uint8_t *, ptrdiff_t,  ptrdiff_t,  int16_t *, const int,  const int,  const int)’ {aka ‘void (*)(unsigned char *, unsigned char *, long int,  long int,  short int *, const int,  const int,  const int)’} [-Wincompatible-pointer-types]
1074 |         sao->band_filter[i] = FUNC(sao_band_filter);
|                             ^ …

build: fix build for sao and constify more parameters

---

libavcodec/vvc/vvc_ctu.c
libavcodec/vvc/vvc_filter.c
libavcodec/vvc/vvc_inter.c
libavcodec/vvc/vvc_mvs.c
libavcodec/vvc/vvc_mvs.h
libavcodec/vvc/vvc_refs.c
libavcodec/vvc/vvc_refs.h
libavcodec/vvc/vvcdec.c
libavcodec/vvc/vvcdec.h

this will fix the round 2 round issue for ci
We parser slice header and reference list in the main thread. And use it in other threads. Since the reference list pointer will change from slice to slice, we need to move it to slice context"
fixes https://github.com/ffvvc/FFmpeg/issues/55

inter: move refPicList from FrameContext to SliceContext

---

libavcodec/cbs_h266.h
libavcodec/cbs_h266_syntax_template.c
libavcodec/vvc/vvc_cabac.c
libavcodec/vvc/vvc_ctu.c
libavcodec/vvc/vvc_ctu.h
libavcodec/vvc/vvc_intra.c
libavcodec/vvc/vvc_itx_1d.c
libavcodec/vvc/vvc_itx_1d.h
libavcodec/vvc/vvc_ps.c
libavcodec/vvc/vvc_ps.h
libavcodec/vvc/vvc_thread.c
libavcodec/vvc/vvcdsp.h
libavcodec/vvc/vvcdsp_template.c

This PR implements the VVCv2 range extension, which allows for increased dynamic ranges. This PR is branched off #90 for the time-being, but can be rebased if we find a better solution on resolution of [VVC #1602](https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/1602).
The range extension is made up of five parts. The status of each of these in this branch is as below:
Additionally, the the range extension syntax elements have been added to the CBS and parsed. See the table in https://github.com/ffvvc/FFmpeg/issues/83#issuecomment-1575658232 for which bitstreams test which features.

WIP: Range extension

---

libavcodec/vvc/vvc_ctu.c
libavcodec/vvc/vvc_ctu.h
libavcodec/vvc/vvc_filter.c
libavcodec/vvc/vvc_inter.c
libavcodec/vvc/vvc_inter.h
libavcodec/vvc/vvc_mvs.c
libavcodec/vvc/vvc_refs.c
libavcodec/vvc/vvc_refs.h
libavcodec/vvc/vvc_thread.c
libavcodec/vvc/vvcdec.c
libavcodec/vvc/vvcdec.h

this will greatly improve performance in some cases.
Clip|Before|After|Delta
-|-|-|-
RitualDance_1920x1080_60_10_420_32_LD.266 	|159.3	|166.7	|4.65%
Tango2_3840x2160_60_10_420_27_RA.266 	    |39	    |38	    |-2.56%
RitualDance_1920x1080_60_10_420_37_RA.266 	|167	|173.7	|4.01%
Tango2_3840x2160_60_10_420_27_LD.266 	    |41	    |42.7	|4.15%
BQTerrace_1920x1080_60_10_420_22_RA.vvc 	|83.7	|94.7	|13.14%
NovosobornayaSquare_1920x1080.bin 	        |155	|200.7	|29.48%
Chimera_8bit_1080P_1000_frames.vvc 	        |191.7	|199.3	|3.96%
fixes https://github.com/ffvvc/FFmpeg/issues/23

make parser and inter blockless

---

libavcodec/x86/Makefile
libavcodec/x86/vvc_mc.asm
libavcodec/x86/vvcdsp_init.c
tests/checkasm/Makefile
tests/checkasm/checkasm.c
tests/checkasm/checkasm.h
tests/checkasm/vvc_mc.c

put_vvc_luma_hv_10_C: 15480181
put_vvc_luma_hv_10_avx512icl: 1649488
ff_vvc_put_vvc_luma_h_16_C_w4_h4:                846
ff_vvc_put_vvc_luma_h_16_avx512icl_w4_h4:        137
ff_vvc_put_vvc_luma_h_16_C_w4_h8:               1591
ff_vvc_put_vvc_luma_h_16_avx512icl_w4_h8:        221
ff_vvc_put_vvc_luma_h_16_C_w4_h16:              2456
ff_vvc_put_vvc_luma_h_16_avx512icl_w4_h16:       329
ff_vvc_put_vvc_luma_h_16_C_w4_h32:              3652
ff_vvc_put_vvc_luma_h_16_avx512icl_w4_h32:       565
ff_vvc_put_vvc_luma_h_16_C_w4_h64:              4842
ff_vvc_put_vvc_luma_h_16_avx512icl_w4_h64:       800
ff_vvc_put_vvc_luma_h_16_C_w4_h128:            11294
ff_vvc_put_vvc_luma_h_16_avx512icl_w4_h128:     1548
ff_vvc_put_vvc_luma_h_16_C_w8_h4:                577
ff_vvc_put_vvc_luma_h_16_avx512icl_w8_h4: …

MC AVX2/AVX512ICL

---

libavcodec/vvc/vvc_ctu.c
libavcodec/vvc/vvc_ctu.h

It seems as though the `V_DIAG` mode should not be used when using Direct Mode MIP. To be honest, I don't see how this is implemented in the specification, so there's probably a better way to implement this. The only relevant clause I see in the specification is:
>If treeType is equal to SINGLE_TREE, sps_chroma_format_idc is equal to 3, intra_chroma_pred_mode is equal to 4, and IntraMipFlag[ xCb ][ yCb ] is equal to 1, the following applies:
>– The MIP chroma direct mode flag MipChromaDirectFlag[ xCb ][ yCb ] is set equal to 1.
>– The chroma intra prediction mode IntraPredModeC[ xCb ][ yCb ] is set equal to IntraPredModeY[ xCb ][ yCb ].
however this is already implemented and has the additional condition `intra_chroma_pred_mode == 4`.
As is, this fix appears to work however. I will make a …

Fix 4:4:4 intra prediction 

---

libavcodec/x86/vvc_sao.asm
libavcodec/x86/vvc_sao_10bit.asm

_Actually_ fixes the doubled PB size constant. Stupid error on my end, to be honest.
Fixes the first part of #119

vvc_sao: proper fix for doubled PB size constant

---

libavcodec/aarch64/Makefile
libavcodec/aarch64/vvcdsp_init_aarch64.c
libavcodec/aarch64/vvcdsp_sao_neon.S
libavcodec/vvc/vvcdsp.c
libavcodec/vvc/vvcdsp.h

I recently got an M1 Pro MacBook Pro (6x Performance Cores, 2x Efficiency Cores). As a distraction and exercise, I ported the HEVC SAO NEON code to VVC.
```
+++++++++ report +++++++++
passed files:
APSMULT_A_MediaTek_4.bit
MTS_LFNST_A_LGE_4.bit
IP_A_Huawei_2.bit
TILE_F_Nokia_2.bit
STILL444_B_ERICSSON_1.bit
JCCR_E_Nokia_1.bit
OPI_A_Nokia_1.bit
10b422_D_Sony_5.bit
LFNST_A_LGE_4.bit
SbTMVP_A_Bytedance_3.bit
APSLMCS_D_Dolby_1.bit
CCALF_D_Sharp_3.bit
ALF_B_Huawei_3.bit
BDOF_A_MediaTek_4.bit
SCALING_A_InterDigital_1.bit
MERGE_A_Qualcomm_2.bit
PDPC_B_Qualcomm_3.bit
LMCS_C_Dolby_1.bit
DCI_A_Tencent_3.bit
DEBLOCKING_B_Sharp_2.bit
ENTHIGHTIER_B_Sony_3.bit
BCW_A_MediaTek_4.bit
QUANT_E_Interdigital_1.bit
MRLP_B_HHI_2.bit
8b420_A_Bytedance_2.bit
MERGE_F_Qualcomm_2.bit
8b422_B_Sony_5.bit …
```

vvc_sao: Add AArch64 NEON accelerated SAO band and edge filters

---

libavcodec/vvc/vvc_inter.c
libavcodec/vvc/vvc_inter_template.c
libavcodec/vvc/vvcdsp.h

3 benifites
1. we can use current put_luma asm code
2. it will reduce asm functions number.
3. we can totally reuse dav1d avg and w_avg code

inter: refact, use avg to simplify bi predict functions

---

libavcodec/vvc/vvc_ctu.c
libavcodec/vvc/vvc_ctu.h
libavcodec/vvc/vvc_refs.c
libavcodec/vvc/vvc_refs.h
libavcodec/vvc/vvc_thread.c
libavcodec/vvc/vvc_thread.h
libavcodec/vvc/vvcdec.c

Using this approach, we do not need to check neighbors' status. Every ready CTU will scheduled based on scores. 
"is_ready" or "is_priority_higher" callback is not needed anymore. 
We may use a lockless executor to reduce multi-thread overhead in the future

Score based parse and inter

---

libavcodec/vvc/vvc_ctu.c
libavcodec/vvc/vvc_ctu.h
libavcodec/vvc/vvc_inter.c
libavcodec/vvc/vvc_thread.c

CLIP|Before|After|Delta|
--|--|--|--|
BQTerrace_1920x1080_60_10_420_22_RA.vvc|141.3|141.3|0.00%|
Chimera_8bit_1080P_1000_frames.vvc	        |287.7	|290.3	|0.90%|
NovosobornayaSquare_1920x1080.bin	        |263.7	|267.3	|1.37%|
RitualDance_1920x1080_60_10_420_32_LD.266	|253.7	|268.3	|5.75%|
RitualDance_1920x1080_60_10_420_37_RA.266	|261.3	|263.3	|0.77%|
Tango2_3840x2160_60_10_420_27_LD.266    	|59	    |60.3	|2.20%|

vvc_thread: report mv progress in parser if we do not have dmvr

---

libavcodec/vvc/vvc_filter.c

`y_ctb` can be zero while `border_pixels`, `w` and `x` are all non-negative, resulting in a left shift of a negative value which is UB.  In the case `y_ctb` is 0, `edges[TOP]` is 1, hence the result is not used, but changing the order of operations removes the UB and makes undefined behaviour sanitizers happy.

lavc/vvc: Fix left shift of negative value

---

libavcodec/vvc/vvc_ctu.h

`IS_SAME_MV` requires motion vectors to be aligned to a multiple of 8 bytes:
https://github.com/ffvvc/FFmpeg/blob/ae5efc8e4b4d3ea0ce673d0ee69e425487591d42/libavcodec/vvc/vvc_mvs.c#L28
This PR adds the same requirement to the definition of MvField.  It fixes errors with UB sanitizers.

lavc/vvc: Fix MvField alignment
